# random number seed
seed: 42

# source data
input:
  in_dir: /data/ML-Project-Data/FAMLI/Datasets/v9
  # name of the project
  # can be one of the following projects
  # FAMLI2_enrolled
  # FAMLI2
  # FAMLI3
  # DXA
  project: FAMLI3

# output data
output:
  # filenames for output files
  out_file: FAMLI3_prototype_twin_selected.csv
  intermediate_file: FAMLI3_prototype_twin_base.csv

# selection parameters
selection:
  # this is output label for twins used for ML
  out_col: TWIN
  # define twins
  twins:
    patients: null
    include:
      # these columns will be used to determine twins
      columns:
        - us_twin
        - NOF
      # do both columns have to have twin value to be a twin?
      operation: and
      # these values determine what will be considered twins
      values:
        - 2
        - 3
      operation: and
    # this value indicates twins
    label: 1
  # everything else is considered as singleton
  singles:
    patients: null
    # this value indicates singletons
    label: 0
    # all instances must have a value for these columns
    # set to null to allow all instances
    enforce:
      columns:
        - GA, ega
        - tag
      operation: and
    # sweep tag filtering
    tags:
      # use this column to read sweep tag
      column: tag
      # these are valid sweep tags
      include_biometric: true
      include_unknown: false
  # exception file lists PIDs to force classify
  # or exclude from both twins and singles set
  # use value from column "as is"
  exception:
    except_dir: /data/ML-Raw-Data/FAMLI/FAMLI_corrections_GHL
    filename: FAMLI3_Twins_20250417.csv
    exclude_label: -99

# instance table spreadsheet
it_file:
  filename: FAMLI3_prototype_tag.csv
  rows: 187321
  columns:
    - PID
    - StudyID
    # - relpath
    # - StudyDate
    - filename
    - Manufacturer
    - ManufacturerModelName
    # - DeviceSerialNumber
    # - StudyTime
    # - SOPInstanceUID
    # - StudyInstanceUID
    # - SOPClassUID
    # - NumberOfFrames
    # - Rows
    # - Columns
    - tag
    # - PhysicalDeltaX
    # - PhysicalDeltaY
    - file_type
    - NOF
    - CRL
    # - CRL_var
    - BPD
    # - BPD_var
    - HC
    # - HC_var
    - AC
    # - AC_var
    - FL
    # - FL_var
    - GA
    # - GA_EDD
    # - GA_EFW
    # - CUA
    # - EFW
    # - EFWpr
    # - Gpr
    # - LMP
    # - AFI
    # - AFq1
    # - AFq2
    # - AFq3
    # - AFq4
    # - DVP
    - ega
    # - us_loc
    - us_twin
    # - us_fhr
    # - us_wks
    # - us_day
    # - us_lie
    # - us_bpa
    # - us_bpb
    # - us_hca
    # - us_hcb
    # - us_aca
    # - us_acb
    # - us_fla
    # - us_flb
    # - us_tcda
    # - us_tcdb
    # - us_efw
    # - us_perc
    # - us_q1
    # - us_q2
    # - us_q3
    # - us_q4
    # - us_dvp_ge
    # - us_plac
    # - us_previa
    # - found_in
    # - exam_source
    - exam_dir
    - orig_frames
    - orig_channels
    - orig_height
    - orig_width
    - scal_frames
    - scal_channels
    - scal_height
    - scal_width
    - bbox_x0
    - bbox_y0
    - bbox_x1
    - bbox_y1
    - fail_reason
