# source directory for CRF data
input:
  # root directory for CRF data
  raw_dir: /data/ML-Raw-Data/FAMLI/
  # case report forms file name
  crf_file: FAMLI2_case_report_forms.xlsx
  crf_sheet: FAMLI2 CRFs
  # tabular structured reports file name(s)
  sr_files:
    - FAMLI2_enrolled_GE_Clarius_Exam_Data.csv
    - FAMLI2_enrolled_Sonosite_Exam_Data.csv
  # name of the project, can be one of the following
  # FAMLI2_enrolled
  # FAMLI2
  # FAMLI3
  # DXA
  project: FAMLI2_enrolled

# output data
output:
  # directory to write the output data
  out_dir: /data/ML-Project-Data/FAMLI/Datasets/v9
  out_file: FAMLI2_enrolled_Exam_Data.csv

# columns containing critical information
# if missing in structured reports, set it to null
# if should not be used, set it to null
crf_dict:
  columns:
    - pidscan
    - us_famscan
    - eligible
    - edd_date
    - ega
    - sc_date_date
    - age
    - sc_us_date_date
    - sc_us_edd_date
    - sc_ht
    - sc_wt
    - sc_first_wt
    - sc_first_anc_date
    - lmp_certain
    - iugr_priorscan
    - us_date_date
    - us_fh
    - us_loc
    - us_twin
    - us_fhr
    - us_lie
    - us_dvp
    - us_plac
    - us_previa
    - us_sweep
    - us_3d
    - us_dop
    - us_butter_blind
    - us_clarius_blind
    - sonographer
    - novice
    - fetut_anom
    - single_iup
  rename_columns:
    pidscan: StudyID
