# source for instance data
input:
  raw_dir: /data/ML-Raw-Data/FAMLI/GA_NEJME/
  csv_dir: /data/ML-Project-Data/FAMLI/Datasets/v0
  csv_file: prototype_test.csv

output:
  out_dir: /data/ML-Project-Data/FAMLI/Datasets/v4
  out_file: test.csv

# image parameters
# image size: size of the output image
# channels: number of channels in output image
# dtype: data type of the output image
# alpha: pixel resolution of the output image
image:
  img_size: 288
  channels: 1
  dtype: uint8
  alpha: 0.075

# overall processing parameters
processing:
  cores: 48
  batch_size: 1000
