"""
RandomGammaAugmentation.py

This file contains the RandomGammaAugmentation class, which applies random gamma
correction to an image.

Author: Olivia Zahn

This software is licensed under the MIT license. See LICENSE.txt in the root of
the repository for details.
"""
import numpy as np
from torchvision.transforms.v2.functional import adjust_gamma


class RandomGammaAugmentation:
    """
    Applies random gamma correction to an image. The gamma value is generated by
    exponentiating a variable that is sampled from a zero-centered normal distribution
    with a user-specified standard deviation.

    Parameters:
        std (float):    The standard deviation of the normal distribution used to
                        sample gamma values.

    Methods:
        __call__(img):  Applies gamma correction to the input image.

    """
    def __init__(self, std: float = 0.1):
        self.mean = 0.0
        self.std = std

    def __call__(self, img):
        gamma = np.exp(np.random.normal(self.mean, self.std))
        return adjust_gamma(img, gamma)
